version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DEBUG=True
      - PORT=5000
      - API_PREFIX=/api/v1
      - JWT_SECRET_KEY=dev-secret-key-change-in-production
      - JWT_ACCESS_TOKEN_EXPIRES=28800
      - SERVER=${SERVER}
      - DATABASE=${DATABASE}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - LOG_LEVEL=DEBUG
    volumes:
      - ./app:/app/app
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD:-YourStrong@Passw0rd}
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mssql_data:
  redis_data:

networks:
  app-network:
    driver: bridge 